language: scala
scala:
- 2.12.8
jdk:
- openjdk8
sudo: required
dist: xenial
cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.coursier"
  - "$HOME/.sbt"
script:
- sbt ++$TRAVIS_SCALA_VERSION test
after_success:
- test $PUBLISH == "true" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH
  == "master" && GPG_WARN_ON_FAILURE=true sbt +publishSigned
before_install:
- openssl aes-256-cbc -K $encrypted_8d7abf919097_key -iv $encrypted_8d7abf919097_iv
  -in project/.keyring.asc.enc -out project/.keyring.asc -d
- gpg -a --import project/.keyring.asc